### ISSUE TITLE
SVG is not displayed correctly using redirect protocol on "hireable.me"

### ISSUE THREAD

**Issue by nguyenph88** [hiendv/hireable#5]
For now, when displaying the badge on the github README using the hireable.me domain, the image is not displayed correctly. Meaning that when inserting the image to github, it's an error. However, it displays correctly when going to the direct link.

I did some investigation around, the `content-type` is returned as `text/html`

```
root@auto-commit:~# curl -i http://www.hireable.me/nguyenph88/
HTTP/1.1 200 OK
Server: nginx
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
```

```
root@auto-commit:~# curl -i https://hireable.0x1115.org/nguyenph88/
HTTP/1.1 200 OK
Cache-Control: private
Content-Length: 738
Content-Type: image/svg+xml
Date: Thu, 01 Sep 2016 20:51:30 GMT
Etag: 5b990fd6584ca4a2c5efa9860906c761
```

It's either the configuration with `camo` or the default behavior when using `redirect` protocol for domain hireable.me. Since I do not have control over the server, I would like to ask your help for the workaround for this on your end.

Alternatively, i can spin up another droplet and run your code on it, if this issue takes long enough for you. Thanks,

**Comment by hiendv** [comment]
First of all, thank you for your help :gift: 
Instead of a redirection, `http://www.hireable.me/<username>` gives an iframe and that's the reason causing images to not show.
I thought about a `CNAME/A` record. I'm using CloudFlare to hide the original IP address of the server. To perform `CNAME` resolution, `hireable.me` have to be on CloudFlare and it's inconvenient for you.
Is there any way to properly setup a 301 or 302 redirection from your end?

**Comment by nguyenph88** [comment]
Since I cannot CNAME/A to your real IP, i will set the URL redirect to unmasked. I tried to avoid this approach while setting up the DNS because the URL will show the destination URL, which is not a good practice in DNS re-routing.

Problem solved now! You can merge, thanks! :)

**Comment by hiendv** [comment]
Agreed. I am wondering if there is any possibility for me to add the domain to my CloudFlare account while maintaining your authorship of it.
